### ISSUE TITLE
The controller should stop the reconciliation of a resource having the pending plan

### ISSUE THREAD

**Issue by chanwit** [chanwit/tf-controller#19]

**Comment by tomhuang12** [comment]
I can try this one. Is this breaking down the if statements into separate ones here: 
https://github.com/chanwit/tf-controller/blob/main/controllers/terraform_controller.go#L132

**Comment by chanwit** [comment]
Hi @tomhuang12 
It's fixed already in v0.6.0, by 274e70bb81ab54bb546b0d808bff8eb9e284fc4f.

But it would be great if you could check to see if the problem still persists.
Here's steps to reproduce,
- set `.spec.interval` to be like 1m or 30s
- make changes
- the status should be `Plan generated: set ...`
- wait for like 5minutes to see it's still wait for a manual approval.

**Comment by tomhuang12** [comment]
I just gave it a test. It is indeed not reconciling the `Terraform` object when it has a plan. These are steps I did and the result:
1. Apply `Terraform` object
2. Status shows `Plan generated: set approvePlan: "plan-main-60b7dfe60b" to approve this plan.`
3. Made changes to the terraform files being planned
4. Wait for 5 minutes
5. `Terraform` object status still shows `Plan generated: set approvePlan: "plan-main-60b7dfe60b" to approve this plan.`. The `lastTransitionTime` for the `Plan generated` is the time from step 2. 

I think it should create another plan if the terraform files got changed. I know currently we can't see the plan result but in the future when a user sees the result and realized that they need to make a change. They make that change but since it is not being reconciled, it wouldn't generate a new plan unless it is applied first. 

Other questions I have will going through this:
- Is the terraform output stored somewhere? I don't see it as a secret.
- Does it pick up .tfvars from the directory?

Hope this helps. Thanks!

**Comment by chanwit** [comment]
> I think it should create another plan if the terraform files got changed. 

Yes, the ability to re-plan haven't been defined yet in this scenario, where a plan got generated. Your tested scenario is perfect to be the specification of the re-plan behavior.

> Is the terraform output stored somewhere? I don't see it as a secret.
It won't give you any output, unless you specify `.spec.writeOutputsToSecret` with a Secret name. It's by designed to prevent leaking of sensitive outputs.

> Does it pick up .tfvars from the directory?
Of course, but be careful not to name anything like `generated.auto.tfvars.json`, as it will be overwrite by the controller.

**Comment by tomhuang12** [comment]
Thanks for the answers! I believe this issue can be closed now.

**Comment by chanwit** [comment]
Thanks, Tom!

**Comment by chanwit** [comment]
Hi @tomhuang12 

I thing my previous explanation was wrong.
The change was not re-planed as we thought might be because of the interval of the Source being more than 5m ?
If so, could you try reduce your Source's interval to be like 1m or 30s to double check the effect, please?

**Comment by tomhuang12** [comment]
The source interval was set to 30s when I tested the scenario, and the change was not re-planned. Did it re-plan for you?

**Comment by chanwit** [comment]
You're right. I think the behavior was slight changed by some new logic recently added.
I'll add another spec to describe the new behavior.
